<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Attendance extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $casts = [
        'date'=>'datetime:Y m d H:i',
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::creating(function ($attendance) {
            $attendance->date = now();
            $attendance->title = $attendance->title?? 'Attendance by '.auth()->user()->name;
            $attendance->created_by = auth()->user()->id;
        });
    }

    public function creator(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function subgroup(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Subgroup::class);
    }
//    attendance member many to many relationship
    public function members(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Member::class, 'attendance_member', 'attendance_id', 'member_id');
    }
}
