<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Calender extends Model
{
    protected $guarded = [];
    protected $hidden = ['company_id'];
    use HasFactory;

    public function company()
    {
        return $this->belongsTo(Company::class);
    }
    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::creating(function ($calender) {
            $calender->company_id = auth()->user()->company_id;
        });
    }
}
